# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a7391f410d40c7527003354c89c04422031632313d1a289589ef4dc1688378fccad44d4aed81bd0cc65a2c7fc2cca9bac9cc821ada9a16c21c2666f6d089dbe

test:
  secret_key_base: c21db6d427169b2d54c69c40c51dbb11258d6b1eb7373d7cda6e575a9f4a1805039743ba66af0398d974eb1e192e0c116f3b5aebde870a21ef0220d38274a4af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
